# Generated by Django 5.2.9 on 2026-01-15 09:08

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], db_index=True, max_length=20)),
                ('user_id', models.CharField(db_index=True, help_text='Phone for WhatsApp, ID for Telegram', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақ'), ('en', 'English')], default='ru', max_length=5)),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'user_id'], name='telegram_bo_platfor_566670_idx'), models.Index(fields=['created_at'], name='telegram_bo_created_ca4a75_idx'), models.Index(fields=['last_active_at'], name='telegram_bo_last_ac_77624c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecondaryProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (₸)')),
                ('rooms', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Количество комнат')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь (м²)')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Этаж')),
                ('total_floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего этажей')),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Город')),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Район')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Телефон владельца')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Балкон')),
                ('has_renovation', models.BooleanField(default=False, verbose_name='С ремонтом')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/', verbose_name='Фото')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Векторное представление описания для семантического поиска', null=True)),
            ],
            options={
                'verbose_name': 'Вторичная недвижимость',
                'verbose_name_plural': 'Вторичная недвижимость',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'rooms', 'price'], name='telegram_bo_city_7ea1e0_idx'), models.Index(fields=['is_active', '-created_at'], name='telegram_bo_is_acti_e756bf_idx'), models.Index(fields=['district', '-created_at'], name='telegram_bo_distric_812c3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('property', 'По объекту'), ('bot', 'По работе бота'), ('search', 'По поиску'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('property_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='telegram_bot.botuser')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_intent', models.CharField(default='greeting', help_text='Текущее намерение: greeting, search_objects, consult_location и т.д.', max_length=50)),
                ('search_params', models.JSONField(blank=True, default=dict, help_text='Накопленные параметры поиска: rooms, price, city, district и т.д.')),
                ('conversation_history', models.JSONField(blank=True, default=list, help_text='История сообщений для контекста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Время истечения сессии (опционально)', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='telegram_bot.botuser')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(help_text='Что хочет пользователь', verbose_name='Текст запроса')),
                ('search_params', models.JSONField(blank=True, default=dict, help_text='Параметры поиска на момент создания лида')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('contacted', 'Связались'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], db_index=True, default='new', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Имя менеджера', max_length=100, null=True)),
                ('manager_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='0 = обычный, 5 = срочный', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='telegram_bot.botuser')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='telegram_bo_status_551593_idx'), models.Index(fields=['-priority', '-created_at'], name='telegram_bo_priorit_da0de4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField(verbose_name='Текст запроса')),
                ('detected_intent', models.CharField(max_length=50, verbose_name='Обнаруженное намерение')),
                ('detected_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('detected_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('lifestyle_tags', models.JSONField(default=list, verbose_name='Lifestyle теги')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Уверенность AI')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество результатов')),
                ('bi_group_count', models.IntegerField(default=0, verbose_name='BI Group')),
                ('secondary_count', models.IntegerField(default=0, verbose_name='Вторичка')),
                ('search_duration_ms', models.IntegerField(default=0, verbose_name='Время поиска (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='telegram_bot.botuser')),
            ],
            options={
                'verbose_name': 'Лог поиска',
                'verbose_name_plural': 'Логи поиска',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='telegram_bo_created_512a93_idx'), models.Index(fields=['detected_city', '-created_at'], name='telegram_bo_detecte_d6d46b_idx')],
            },
        ),
    ]
