# Generated by Django 5.2.9 on 2026-01-15 11:19

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bi_uuid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID из API')),
                ('name', models.CharField(max_length=255, verbose_name='Название ЖК')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('city_uuid', models.CharField(db_index=True, max_length=100, verbose_name='UUID Города')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Класс жилья')),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок сдачи')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Цена от')),
                ('website', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True, verbose_name='Фото 400px')),
                ('features', models.JSONField(default=dict, verbose_name='AI Теги')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ЖК',
                'verbose_name_plural': 'ЖК',
                'db_table': 'bi_complexes',
            },
        ),
        migrations.CreateModel(
            name='BIUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bi_uuid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID Квартиры')),
                ('room_count', models.IntegerField(db_index=True, verbose_name='Комнат')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('max_floor', models.IntegerField(null=True, verbose_name='Всего этажей')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Базовая цена')),
                ('price_discount', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Цена со скидкой')),
                ('block_name', models.CharField(blank=True, max_length=100, verbose_name='Блок/Секция')),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок сдачи секции')),
                ('is_active', models.BooleanField(default=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='telegram_bot.bicomplex')),
            ],
            options={
                'verbose_name': 'Квартира в ЖК',
                'verbose_name_plural': 'Квартиры в ЖК',
                'db_table': 'bi_units',
                'indexes': [models.Index(fields=['price_discount', 'room_count'], name='bi_units_price_d_3c0521_idx'), models.Index(fields=['area'], name='bi_units_area_f1eed0_idx')],
            },
        ),
    ]
