# Generated by Django 5.2.9 on 2026-01-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_bicomplex_biunit'),
        ('telegram_bot', '0003_enable_pgvector'),
    ]

    operations = [
    ]
