# Generated by Django 5.2.9 on 2026-01-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_merge_0002_bicomplex_biunit_0003_enable_pgvector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicomplex',
            old_name='website',
            new_name='url',
        ),
        migrations.AddField(
            model_name='bicomplex',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='state',
            field=models.CharField(default='START', max_length=50),
        ),
    ]
