# Generated by Django 5.2.9 on 2026-01-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_bicommercialcomplex_bicommercialunit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bicommercialunit',
            new_name='bi_commerci_price_d_227ae2_idx',
            old_name='bi_commercial_units_price_d_9c4f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='bicommercialunit',
            new_name='bi_commerci_area_c15c5d_idx',
            old_name='bi_commercial_units_area_9f8cd5_idx',
        ),
    ]
