# Generated by Django 5.2.9 on 2026-01-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_rename_bi_commercial_units_price_d_9c4f1e_idx_bi_commerci_price_d_227ae2_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicommercialunit',
            options={'verbose_name': 'Офис/Помещение', 'verbose_name_plural': 'Офисы/Помещения'},
        ),
        migrations.AlterModelOptions(
            name='bicomplex',
            options={'verbose_name': 'ЖК (Жилой)', 'verbose_name_plural': 'ЖК (Жилые)'},
        ),
        migrations.AlterModelOptions(
            name='biunit',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='bicommercialcomplex',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bicommercialcomplex',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bicommercialunit',
            name='bi_uuid',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID Юнита'),
        ),
        migrations.AlterField(
            model_name='bicommercialunit',
            name='room_count',
            field=models.IntegerField(db_index=True, verbose_name='Комнат/Помещений'),
        ),
        migrations.AlterField(
            model_name='bicomplex',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='bicomplex',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bicomplex',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='biunit',
            name='bi_uuid',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID Юнита'),
        ),
        migrations.AlterField(
            model_name='biunit',
            name='room_count',
            field=models.IntegerField(db_index=True, verbose_name='Комнат/Помещений'),
        ),
    ]
