# Generated by Django 5.2.9 on 2026-02-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_add_secondary_property_external_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoriteproperty',
            new_name='telegram_bo_user_id_8abea6_idx',
            old_name='telegram_bo_user_id_0e55ad_idx',
        ),
        migrations.RenameIndex(
            model_name='favoriteproperty',
            new_name='telegram_bo_object__14e271_idx',
            old_name='telegram_bo_object__f0fdb5_idx',
        ),
    ]
