# Generated by Django 5.2.9 on 2026-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_rename_telegram_bo_user_id_0e55ad_idx_telegram_bo_user_id_8abea6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryproperty',
            name='area_kitchen',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='area_living',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолка'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='city_micro_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Микрорайон'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='coordinates_source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Источник координат'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='prices',
            field=models.JSONField(blank=True, default=dict, verbose_name='Цены по валютам'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='prices_m2',
            field=models.JSONField(blank=True, default=dict, verbose_name='Цена за м² по валютам'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='rent_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='rooms_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего комнат (источник)'),
        ),
        migrations.AddField(
            model_name='secondaryproperty',
            name='subtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подтип объекта'),
        ),
    ]
