# Generated by Django 5.2.9 on 2026-04-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_permission_role'),
        ('telegram_bot', '0014_secondaryproperty_area_kitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='dashboard.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram @username без символа @', max_length=100, null=True, verbose_name='Username'),
        ),
    ]
