# Generated by Django 5.2.9 on 2026-04-28 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0015_botuser_role_botuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('objects_shown', models.IntegerField(default=0, verbose_name='Объектов показано (итого)')),
                ('apartments_shown', models.IntegerField(default=0, verbose_name='Квартир показано')),
                ('commercial_shown', models.IntegerField(default=0, verbose_name='Коммерческих показано')),
                ('primary_shown', models.IntegerField(default=0, verbose_name='Первичного рынка показано')),
                ('secondary_shown', models.IntegerField(default=0, verbose_name='Вторичного рынка показано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='telegram_bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Суточная статистика выдачи',
                'verbose_name_plural': 'Суточная статистика выдачи',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='telegram_bo_user_id_fa600b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
