# Generated by Django 5.2.9 on 2026-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0016_dailyusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusagelog',
            name='bonus_limit_daily',
            field=models.IntegerField(default=0, verbose_name='Бонус к суточному лимиту'),
        ),
    ]
