# Generated by Django 5.2.9 on 2026-05-25 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API токен',
                'verbose_name_plural': 'API токены',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название анкеты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('motivation_text', models.TextField(blank=True, help_text='Текст бонуса/мотивации, который показывается пользователю.', verbose_name='Мотивация прохождения')),
                ('bonus_extra_limit', models.IntegerField(default=0, help_text='Сколько дополнительных объектов получает пользователь после прохождения анкеты.', verbose_name='Бонус к суточному лимиту (объектов)')),
                ('trigger_type', models.CharField(choices=[('manual', 'Только вручную'), ('search_count', 'После количества поисков'), ('objects_count', 'После количества полученных объектов')], default='manual', max_length=20, verbose_name='Момент показа анкеты')),
                ('trigger_search_count', models.IntegerField(default=0, help_text='Используется если trigger_type=search_count', verbose_name='Показать после N поисков')),
                ('trigger_objects_count', models.IntegerField(default=0, help_text='Используется если trigger_type=objects_count', verbose_name='Показать после N полученных объектов')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Анкета обратной связи',
                'verbose_name_plural': 'Анкеты обратной связи',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Кодовое имя')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('properties', 'Объекты недвижимости'), ('market', 'Тип рынка'), ('bot', 'Функции бота'), ('contacts', 'Контакты'), ('data', 'Данные и аналитика')], db_index=True, default='bot', max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('limit_apartments_daily', models.IntegerField(default=10, help_text='Максимальное количество квартир, выдаваемых боту в сутки', verbose_name='Лимит квартир/сутки')),
                ('limit_commercial_daily', models.IntegerField(default=10, help_text='Максимальное количество коммерческих объектов в сутки', verbose_name='Лимит коммерческой недвижимости/сутки')),
                ('limit_primary_daily', models.IntegerField(default=10, help_text='Максимальное количество объектов первичного рынка в сутки', verbose_name='Лимит первичного рынка/сутки')),
                ('limit_secondary_daily', models.IntegerField(default=10, help_text='Максимальное количество объектов вторичного рынка в сутки', verbose_name='Лимит вторичного рынка/сутки')),
                ('limit_total_daily', models.IntegerField(default=20, help_text='Общий суточный лимит выдачи всех объектов', verbose_name='Общий лимит объектов/сутки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BIGroupLeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('complex_uuid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UUID ЖК')),
                ('complex_name', models.CharField(blank=True, max_length=255, verbose_name='Название ЖК')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета (TG username/ID)')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Ответ API')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Лог лидов BI Group CRM',
                'verbose_name_plural': 'Логи лидов BI Group CRM',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['success', '-created_at'], name='dashboard_b_success_02bb4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, verbose_name='Ключ')),
                ('channel', models.CharField(choices=[('all', 'Все каналы'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20, verbose_name='Канал')),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақ'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты бота',
                'ordering': ['key', 'channel', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('key', 'channel', 'locale'), name='unique_bot_text_key_channel_locale')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('single_choice', 'Один вариант'), ('multi_choice', 'Несколько вариантов'), ('rating', 'Оценка (1-5)')], default='text', max_length=20, verbose_name='Тип вопроса')),
                ('options', models.JSONField(blank=True, default=list, help_text='Список строк для single_choice/multi_choice.', verbose_name='Варианты ответа')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.feedbacksurvey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Вопрос анкеты',
                'verbose_name_plural': 'Вопросы анкеты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('answer_rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('answer_options', models.JSONField(blank=True, default=list, verbose_name='Выбранные варианты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.feedbacksurveyquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ анкеты',
                'verbose_name_plural': 'Ответы анкет',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начата'), ('completed', 'Завершена')], default='started', max_length=20, verbose_name='Статус')),
                ('bonus_applied', models.BooleanField(default=False, verbose_name='Бонус применен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.feedbacksurvey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Прохождение анкеты',
                'verbose_name_plural': 'Прохождения анкет',
                'ordering': ['-created_at'],
            },
        ),
    ]
