# Generated by Django 5.2.9 on 2026-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Кодовое имя')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('properties', 'Объекты недвижимости'), ('market', 'Тип рынка'), ('bot', 'Функции бота'), ('contacts', 'Контакты'), ('data', 'Данные и аналитика')], db_index=True, default='bot', max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('limit_apartments_daily', models.IntegerField(default=10, help_text='Максимальное количество квартир, выдаваемых боту в сутки', verbose_name='Лимит квартир/сутки')),
                ('limit_commercial_daily', models.IntegerField(default=10, help_text='Максимальное количество коммерческих объектов в сутки', verbose_name='Лимит коммерческой недвижимости/сутки')),
                ('limit_primary_daily', models.IntegerField(default=10, help_text='Максимальное количество объектов первичного рынка в сутки', verbose_name='Лимит первичного рынка/сутки')),
                ('limit_secondary_daily', models.IntegerField(default=10, help_text='Максимальное количество объектов вторичного рынка в сутки', verbose_name='Лимит вторичного рынка/сутки')),
                ('limit_total_daily', models.IntegerField(default=20, help_text='Общий суточный лимит выдачи всех объектов', verbose_name='Общий лимит объектов/сутки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='dashboard.permission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
    ]
