# Generated by Django 5.2.9 on 2026-05-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('telegram_bot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksurveysubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to='telegram_bot.botuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='feedbacksurveyanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.feedbacksurveysubmission', verbose_name='Прохождение'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='dashboard.permission', verbose_name='Разрешения'),
        ),
        migrations.AddConstraint(
            model_name='feedbacksurveyquestion',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='unique_question_order_per_survey'),
        ),
        migrations.AddIndex(
            model_name='feedbacksurveysubmission',
            index=models.Index(fields=['survey', 'status'], name='dashboard_f_survey__aae67f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksurveysubmission',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_f_user_id_233cbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbacksurveyanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
    ]
