# Generated by Django 5.2.9 on 2026-05-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_permission_role'),
        ('telegram_bot', '0016_dailyusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название анкеты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('motivation_text', models.TextField(blank=True, help_text='Текст бонуса/мотивации, который показывается пользователю.', verbose_name='Мотивация прохождения')),
                ('bonus_extra_limit', models.IntegerField(default=0, help_text='Сколько дополнительных объектов получает пользователь после прохождения анкеты.', verbose_name='Бонус к суточному лимиту (объектов)')),
                ('trigger_type', models.CharField(choices=[('manual', 'Только вручную'), ('search_count', 'После количества поисков'), ('objects_count', 'После количества полученных объектов')], default='manual', max_length=20, verbose_name='Момент показа анкеты')),
                ('trigger_search_count', models.IntegerField(default=0, help_text='Используется если trigger_type=search_count', verbose_name='Показать после N поисков')),
                ('trigger_objects_count', models.IntegerField(default=0, help_text='Используется если trigger_type=objects_count', verbose_name='Показать после N полученных объектов')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Анкета обратной связи',
                'verbose_name_plural': 'Анкеты обратной связи',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, verbose_name='Ключ')),
                ('channel', models.CharField(choices=[('all', 'Все каналы'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20, verbose_name='Канал')),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақ'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты бота',
                'ordering': ['key', 'channel', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('key', 'channel', 'locale'), name='unique_bot_text_key_channel_locale')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('single_choice', 'Один вариант'), ('multi_choice', 'Несколько вариантов'), ('rating', 'Оценка (1-5)')], default='text', max_length=20, verbose_name='Тип вопроса')),
                ('options', models.JSONField(blank=True, default=list, help_text='Список строк для single_choice/multi_choice.', verbose_name='Варианты ответа')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.feedbacksurvey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Вопрос анкеты',
                'verbose_name_plural': 'Вопросы анкеты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начата'), ('completed', 'Завершена')], default='started', max_length=20, verbose_name='Статус')),
                ('bonus_applied', models.BooleanField(default=False, verbose_name='Бонус применен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.feedbacksurvey', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to='telegram_bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прохождение анкеты',
                'verbose_name_plural': 'Прохождения анкет',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('answer_rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('answer_options', models.JSONField(blank=True, default=list, verbose_name='Выбранные варианты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.feedbacksurveyquestion', verbose_name='Вопрос')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.feedbacksurveysubmission', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'Ответ анкеты',
                'verbose_name_plural': 'Ответы анкет',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feedbacksurveyquestion',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='unique_question_order_per_survey'),
        ),
        migrations.AddIndex(
            model_name='feedbacksurveysubmission',
            index=models.Index(fields=['survey', 'status'], name='dashboard_f_survey__aae67f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksurveysubmission',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_f_user_id_233cbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbacksurveyanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
    ]
